import type {
  CrmAccount,
  CrmActivity,
  CrmActivityCandidate,
  CrmDeal,
  CrmFollowUp,
  CrmSettings,
  CrmStage,
} from "@/lib/crm/types";

export const CRM_REVIEW_NOW = new Date("2026-07-28T15:00:00.000Z");

export const CRM_REVIEW_OWNERS = {
  brandon: { id: "owner-brandon", name: "Brandon Clymer", initials: "BC" },
  taylor: { id: "owner-taylor", name: "Taylor Morgan", initials: "TM" },
  jordan: { id: "owner-jordan", name: "Jordan Lee", initials: "JL" },
} as const;

export const CRM_REVIEW_ACCOUNTS: CrmAccount[] = [
  {
    companyId: "company-riverview",
    name: "Riverview Health",
    lifecycleStage: "prospect",
    owner: CRM_REVIEW_OWNERS.brandon,
    healthStatus: "stale",
    healthReason: "Follow-up overdue by 5 days.",
    healthEvaluatedAt: "2026-07-28T06:00:00.000Z",
    lastMeaningfulActivityAt: "2026-06-29T14:30:00.000Z",
    nextFollowUpAt: "2026-07-23",
    openDealValue: 1850000,
    rowVersion: 4,
  },
  {
    companyId: "company-varsity",
    name: "Varsity Brands",
    lifecycleStage: "active_client",
    owner: CRM_REVIEW_OWNERS.taylor,
    healthStatus: "watch",
    healthReason: "No meaningful activity in 18 days.",
    healthEvaluatedAt: "2026-07-28T06:00:00.000Z",
    lastMeaningfulActivityAt: "2026-07-10T17:00:00.000Z",
    nextFollowUpAt: "2026-07-30",
    openDealValue: 720000,
    rowVersion: 2,
  },
  {
    companyId: "company-paradise",
    name: "Paradise Isles",
    lifecycleStage: "prospect",
    owner: CRM_REVIEW_OWNERS.brandon,
    healthStatus: "active",
    healthReason: "Three meaningful activities in the last 14 days.",
    healthEvaluatedAt: "2026-07-28T06:00:00.000Z",
    lastMeaningfulActivityAt: "2026-07-26T15:15:00.000Z",
    nextFollowUpAt: "2026-08-01",
    openDealValue: 2400000,
    rowVersion: 6,
  },
  {
    companyId: "company-west",
    name: "West WH Logistics",
    lifecycleStage: "lead",
    owner: CRM_REVIEW_OWNERS.jordan,
    healthStatus: "unknown",
    healthReason: "No meaningful activity has been recorded.",
    healthEvaluatedAt: "2026-07-27T05:00:00.000Z",
    lastMeaningfulActivityAt: null,
    nextFollowUpAt: "2026-07-29",
    openDealValue: 425000,
    rowVersion: 1,
  },
  {
    companyId: "company-northstar",
    name: "Northstar Distribution",
    lifecycleStage: "past_client",
    owner: CRM_REVIEW_OWNERS.taylor,
    healthStatus: "stale",
    healthReason: "No meaningful activity in 47 days.",
    healthEvaluatedAt: "2026-07-28T06:00:00.000Z",
    lastMeaningfulActivityAt: "2026-06-11T13:00:00.000Z",
    nextFollowUpAt: null,
    openDealValue: 0,
    rowVersion: 3,
  },
];

export const CRM_REVIEW_STAGES: CrmStage[] = [
  {
    id: "stage-lead",
    name: "Lead",
    sortOrder: 10,
    stageType: "open",
    defaultProbability: 10,
  },
  {
    id: "stage-qualified",
    name: "Qualified",
    sortOrder: 20,
    stageType: "open",
    defaultProbability: 30,
  },
  {
    id: "stage-proposal",
    name: "Proposal / Bid",
    sortOrder: 30,
    stageType: "open",
    defaultProbability: 55,
  },
  {
    id: "stage-negotiation",
    name: "Negotiation",
    sortOrder: 40,
    stageType: "open",
    defaultProbability: 75,
  },
  {
    id: "stage-won",
    name: "Won",
    sortOrder: 50,
    stageType: "won",
    defaultProbability: 100,
  },
  {
    id: "stage-lost",
    name: "Lost",
    sortOrder: 60,
    stageType: "lost",
    defaultProbability: 0,
  },
];

export const CRM_REVIEW_DEALS: CrmDeal[] = [
  {
    id: "deal-riverview",
    name: "Automated storage expansion",
    companyId: "company-riverview",
    companyName: "Riverview Health",
    owner: CRM_REVIEW_OWNERS.brandon,
    stageId: "stage-proposal",
    status: "open",
    valueEstimate: 1850000,
    probability: 55,
    expectedCloseDate: "2026-08-21",
    closedAt: null,
    projectId: null,
    projectSyncStatus: "not_started",
    source: "Referral",
    lostReason: null,
    updatedAt: "2026-07-24T12:00:00.000Z",
    rowVersion: 3,
  },
  {
    id: "deal-paradise",
    name: "Paradise Isles distribution center",
    companyId: "company-paradise",
    companyName: "Paradise Isles",
    owner: CRM_REVIEW_OWNERS.brandon,
    stageId: "stage-negotiation",
    status: "open",
    valueEstimate: 2400000,
    probability: 75,
    expectedCloseDate: "2026-08-07",
    closedAt: null,
    projectId: null,
    projectSyncStatus: "not_started",
    source: "Existing relationship",
    lostReason: null,
    updatedAt: "2026-07-27T15:15:00.000Z",
    rowVersion: 5,
  },
  {
    id: "deal-varsity",
    name: "Conveyor controls modernization",
    companyId: "company-varsity",
    companyName: "Varsity Brands",
    owner: CRM_REVIEW_OWNERS.taylor,
    stageId: "stage-qualified",
    status: "open",
    valueEstimate: 720000,
    probability: 30,
    expectedCloseDate: "2026-09-15",
    closedAt: null,
    projectId: null,
    projectSyncStatus: "not_started",
    source: "Outbound",
    lostReason: null,
    updatedAt: "2026-07-10T17:00:00.000Z",
    rowVersion: 2,
  },
  {
    id: "deal-west",
    name: "Warehouse concept study",
    companyId: "company-west",
    companyName: "West WH Logistics",
    owner: CRM_REVIEW_OWNERS.jordan,
    stageId: "stage-lead",
    status: "open",
    valueEstimate: 425000,
    probability: 10,
    expectedCloseDate: "2026-10-01",
    closedAt: null,
    projectId: null,
    projectSyncStatus: "not_started",
    source: "Website",
    lostReason: null,
    updatedAt: "2026-07-27T13:00:00.000Z",
    rowVersion: 1,
  },
  {
    id: "deal-atlas",
    name: "Atlas cold-storage retrofit",
    companyId: "company-atlas",
    companyName: "Atlas Cold Storage",
    owner: CRM_REVIEW_OWNERS.taylor,
    stageId: "stage-won",
    status: "won",
    valueEstimate: 980000,
    probability: 100,
    expectedCloseDate: "2026-07-18",
    closedAt: "2026-07-17T19:00:00.000Z",
    projectId: null,
    projectSyncStatus: "pending",
    source: "Referral",
    lostReason: null,
    updatedAt: "2026-07-17T19:00:00.000Z",
    rowVersion: 7,
  },
  {
    id: "deal-legacy",
    name: "Legacy packaging line",
    companyId: "company-northstar",
    companyName: "Northstar Distribution",
    owner: CRM_REVIEW_OWNERS.taylor,
    stageId: "stage-lost",
    status: "lost",
    valueEstimate: 310000,
    probability: 0,
    expectedCloseDate: "2026-06-30",
    closedAt: "2026-06-25T15:00:00.000Z",
    projectId: null,
    projectSyncStatus: "not_started",
    source: "Existing relationship",
    lostReason: "Budget deferred to next fiscal year.",
    updatedAt: "2026-06-25T15:00:00.000Z",
    rowVersion: 4,
  },
];

export const CRM_REVIEW_ACTIVITIES: CrmActivity[] = [
  {
    id: "activity-1",
    companyId: "company-paradise",
    companyName: "Paradise Isles",
    dealId: "deal-paradise",
    activityType: "meeting",
    subject: "Reviewed final automation scope",
    occurredAt: "2026-07-28T14:00:00.000Z",
    createdBy: "Brandon Clymer",
    recordOrigin: "manual",
    visibilityScope: "standard",
  },
  {
    id: "activity-2",
    companyId: "company-varsity",
    companyName: "Varsity Brands",
    dealId: "deal-varsity",
    activityType: "email",
    subject: "Controls modernization budget range",
    occurredAt: "2026-07-25T16:10:00.000Z",
    createdBy: "Taylor Morgan",
    recordOrigin: "auto",
    visibilityScope: "restricted",
  },
  {
    id: "activity-3",
    companyId: "company-riverview",
    companyName: "Riverview Health",
    dealId: "deal-riverview",
    activityType: "note",
    subject: "Estimator requested updated equipment list",
    occurredAt: "2026-07-24T12:00:00.000Z",
    createdBy: "Brandon Clymer",
    recordOrigin: "manual",
    visibilityScope: "standard",
  },
  {
    id: "activity-4",
    companyId: "company-paradise",
    companyName: "Paradise Isles",
    dealId: "deal-paradise",
    activityType: "call",
    subject: "Confirmed decision meeting",
    occurredAt: "2026-07-23T18:30:00.000Z",
    createdBy: "Brandon Clymer",
    recordOrigin: "manual",
    visibilityScope: "standard",
  },
];

export const CRM_REVIEW_FOLLOW_UPS: CrmFollowUp[] = [
  {
    id: "task-1",
    companyId: "company-riverview",
    dealId: "deal-riverview",
    title: "Send revised equipment allowance",
    dueDate: "2026-07-23",
    assignee: "Brandon Clymer",
    status: "open",
    priority: "urgent",
  },
  {
    id: "task-2",
    companyId: "company-varsity",
    dealId: "deal-varsity",
    title: "Schedule controls discovery",
    dueDate: "2026-07-30",
    assignee: "Taylor Morgan",
    status: "in_progress",
    priority: "high",
  },
  {
    id: "task-3",
    companyId: "company-paradise",
    dealId: "deal-paradise",
    title: "Confirm commercial terms",
    dueDate: "2026-08-01",
    assignee: "Brandon Clymer",
    status: "open",
    priority: "high",
  },
];

export const CRM_REVIEW_CANDIDATES: CrmActivityCandidate[] = [
  {
    id: "candidate-1",
    sourceSystem: "outlook",
    sourceExternalKey: "outlook-4381",
    contentHash: "sha256-a",
    proposedCompanyId: "company-riverview",
    proposedCompanyName: "Riverview Health",
    subject: "Re: automated storage equipment list",
    matchConfidence: 0.96,
    matchSignals: ["Exact participant email", "Known company domain"],
    visibilityScope: "restricted",
    status: "pending",
    occurredAt: "2026-07-28T13:14:00.000Z",
  },
  {
    id: "candidate-2",
    sourceSystem: "fireflies",
    sourceExternalKey: "ff-paradise-72",
    contentHash: "sha256-b",
    proposedCompanyId: "company-paradise",
    proposedCompanyName: "Paradise Isles",
    subject: "Paradise Isles commercial review",
    matchConfidence: 0.88,
    matchSignals: ["Exact attendee email", "Opportunity name in title"],
    visibilityScope: "standard",
    status: "pending",
    occurredAt: "2026-07-27T18:00:00.000Z",
  },
  {
    id: "candidate-3",
    sourceSystem: "teams",
    sourceExternalKey: "teams-west-19",
    contentHash: "sha256-c",
    proposedCompanyId: "company-west",
    proposedCompanyName: "West WH Logistics",
    subject: "Possible warehouse concept discussion",
    matchConfidence: 0.62,
    matchSignals: ["Fuzzy company name", "Warehouse topic"],
    visibilityScope: "private_source",
    status: "pending",
    occurredAt: "2026-07-27T15:30:00.000Z",
  },
];

export const CRM_REVIEW_SETTINGS: CrmSettings = {
  meaningfulActivityTypes: ["call", "email", "meeting"],
  activeDays: 14,
  watchDays: 30,
  staleDealDays: 30,
  reportingTimezone: "America/Indianapolis",
  autoAcceptEnabled: false,
  freeEmailDomains: [
    "gmail.com",
    "outlook.com",
    "hotmail.com",
    "yahoo.com",
    "icloud.com",
  ],
};
