"use client";

import { useCallback, useEffect, useState } from "react";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ErrorState } from "@/components/ds";
import { SectionRuleHeading } from "@/components/layout/spacing";
import { ApiError, apiFetch } from "@/lib/api-client";
import type { ExecutiveClaimLineageResult } from "@/lib/executive/executive-claim-lineage";
import type { ExecutiveSystemHealth } from "@/lib/executive/executive-system-health";

const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const timestamp = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "Not recorded";

export function ExecutiveOperatingSystemDetail({ briefId }: { briefId: string }) {
  const [health, setHealth] = useState<ExecutiveSystemHealth | null>(null); const [error, setError] = useState<string | null>(null); const [selectedClaim, setSelectedClaim] = useState<string | null>(null); const [lineage, setLineage] = useState<ExecutiveClaimLineageResult | null>(null); const [loadingLineage, setLoadingLineage] = useState(false);
  const refresh = useCallback(async () => { try { setError(null); setHealth(await apiFetch<ExecutiveSystemHealth>("/api/executive/system-health", { cache: "no-store" })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Executive system health could not be loaded."); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  async function explain(claimId: string) { setSelectedClaim(claimId); setLineage(null); setLoadingLineage(true); try { setLineage(await apiFetch<ExecutiveClaimLineageResult>(`/api/executive/claims/${claimId}/lineage?briefId=${briefId}`, { cache: "no-store" })); } catch (reason) { const diagnostic = reason instanceof ApiError && reason.status === 409 ? reason.body.details as ExecutiveClaimLineageResult : null; if (diagnostic?.state === "lineage_unavailable") setLineage(diagnostic); else { const message = reason instanceof Error ? reason.message : "Lineage could not be loaded."; setLineage({ state: "lineage_unavailable", claimId, missingStage: "source", owner: "Executive lineage owner", recoveryPath: "Inspect the canonical lineage API diagnostic.", message }); } } finally { setLoadingLineage(false); } }
  return <section className="mt-12 space-y-8 border-t border-border pt-8" aria-labelledby="operating-system-heading">
    <div><SectionRuleHeading label="Operating system" className="mb-1" /><p id="operating-system-heading" className="text-sm text-muted-foreground">Canonical flow, accountable owners, and exceptions that affect an executive decision.</p></div>
    {error ? <ErrorState title="Executive health needs attention" error={error} className="py-2" /> : null}
    {health ? <><div className="divide-y divide-border" aria-label="Operating system map">{health.nodes.map((node) => <div key={node.id} className="grid gap-1 py-4 sm:grid-cols-[minmax(0,1fr)_minmax(10rem,0.7fr)_auto]"><div><p className="text-sm font-medium text-foreground">{node.title}</p><p className="mt-1 text-xs text-muted-foreground">{node.affectedSurface}</p></div><p className="text-sm text-muted-foreground">{node.owner}</p><p className="text-xs text-muted-foreground sm:text-right">{node.health === "healthy" ? "Healthy" : "Needs recovery"} · {timestamp(node.lastSuccessfulUpdate)}</p></div>)}</div>
      {health.claimIds.length ? <div className="flex flex-wrap gap-2"><p className="mr-2 self-center text-sm text-muted-foreground">Material claims</p>{health.claimIds.map((claimId) => <Button key={claimId} size="sm" variant="outline" onClick={() => void explain(claimId)}>Explain claim</Button>)}</div> : null}
      {health.exceptions.length ? <section aria-labelledby="health-exceptions-heading"><SectionRuleHeading label="Health exceptions" className="mb-1" /><p id="health-exceptions-heading" className="text-sm text-muted-foreground">Only conditions with a decision or delivery consequence are shown.</p><div className="mt-3 divide-y divide-border">{health.exceptions.map((exception) => <div key={exception.id} className="py-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="text-sm font-medium text-foreground">{exception.title}</p><p className="text-xs text-muted-foreground">{title(exception.businessImpact)}</p></div><p className="mt-1 text-sm text-muted-foreground">{exception.detail}</p><p className="mt-2 text-xs text-muted-foreground">Owner: {exception.owner} · Recovery: {exception.recoveryPath}</p></div>)}</div></section> : <p className="text-sm text-muted-foreground">No decision-impacting health exceptions are currently recorded.</p>}</> : <p className="text-sm text-muted-foreground">Loading operating system health…</p>}
    <Dialog open={Boolean(selectedClaim)} onOpenChange={(open) => { if (!open) { setSelectedClaim(null); setLineage(null); } }}><DialogContent className="max-h-screen overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Claim lineage</DialogTitle></DialogHeader>{loadingLineage ? <p className="text-sm text-muted-foreground">Loading immutable lineage…</p> : lineage?.state === "ready" ? <div className="divide-y divide-border">{lineage.stages.map((stage) => <div key={stage.id} className="py-4"><p className="text-sm font-medium text-foreground">{stage.title}</p><p className="mt-1 text-sm text-muted-foreground">{stage.detail}</p><p className="mt-2 text-xs text-muted-foreground">Owner: {stage.owner} · Evidence: {stage.evidenceId} · {timestamp(stage.updatedAt)}</p>{stage.href ? <a className="mt-2 inline-block text-xs text-primary underline-offset-4 hover:underline" href={stage.href} target="_blank" rel="noreferrer">Open source evidence</a> : null}</div>)}</div> : lineage ? <ErrorState title={`Lineage unavailable: ${title(lineage.missingStage)}`} error={`${lineage.message} Recovery owner: ${lineage.owner}. ${lineage.recoveryPath}`} /> : null}</DialogContent></Dialog>
  </section>;
}
