"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ErrorState } from "@/components/ds";
import { SectionRuleHeading } from "@/components/layout/spacing";
import { apiFetch } from "@/lib/api-client";
import type { ExecutiveConflictClaim, ExecutiveConflictFeed, ExecutiveConflictItem } from "@/lib/executive/executive-conflicts";

type ClaimForm = { label: string; statement: string; authority: "authoritative" | "observed" | "predicted"; freshness: "fresh" | "stale" | "partial" | "unknown"; sourceId: string; sourceHash: string };
type CreateForm = { attentionId: string; domain: "finance" | "schedule_operations" | "project" | "executive_priority"; subject: string; priority: "critical" | "high" | "medium" | "low"; impactOfDelay: string; accountableResolverLabel: string; dueAt: string; claims: [ClaimForm, ClaimForm] };

const blankClaim = (): ClaimForm => ({ label: "", statement: "", authority: "authoritative", freshness: "fresh", sourceId: "", sourceHash: "" });
const blankForm = (): CreateForm => ({ attentionId: "", domain: "finance", subject: "", priority: "high", impactOfDelay: "", accountableResolverLabel: "", dueAt: "", claims: [blankClaim(), blankClaim()] });
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const date = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));

function ClaimRow({ claim }: { claim: ExecutiveConflictClaim }) {
  return <div className="grid gap-2 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:gap-6">
    <div className="min-w-0"><p className="text-sm font-medium text-foreground">{claim.label}</p><p className="mt-1 text-sm text-muted-foreground">{claim.statement || claim.sourceExcerpt || "No statement recorded."}</p><p className="mt-2 text-xs text-muted-foreground">Evidence: {claim.sourceType} · {claim.sourceId}{claim.assertedAt ? ` · asserted ${date(claim.assertedAt)}` : ""}</p></div>
    <p className="text-xs text-muted-foreground sm:text-right">{label(claim.authority)}<br />{label(claim.freshness)}</p>
  </div>;
}

function ClaimInputs({ index, claim, onChange }: { index: number; claim: ClaimForm; onChange: (key: keyof ClaimForm, value: string) => void }) {
  return <fieldset className="space-y-3 border-t border-border pt-4"><legend className="text-sm font-medium text-foreground">Claim {index + 1}</legend>
    <div className="grid gap-3 sm:grid-cols-2"><Input required value={claim.label} onChange={(event) => onChange("label", event.target.value)} placeholder="Claim label" /><Select value={claim.authority} onValueChange={(value) => onChange("authority", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="authoritative">Authoritative</SelectItem><SelectItem value="observed">Observed</SelectItem><SelectItem value="predicted">Predicted</SelectItem></SelectContent></Select></div>
    <Textarea required value={claim.statement} onChange={(event) => onChange("statement", event.target.value)} placeholder="What does this source assert?" className="min-h-20" />
    <div className="grid gap-3 sm:grid-cols-3"><Select value={claim.freshness} onValueChange={(value) => onChange("freshness", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="fresh">Fresh</SelectItem><SelectItem value="stale">Stale</SelectItem><SelectItem value="partial">Partial</SelectItem><SelectItem value="unknown">Unknown</SelectItem></SelectContent></Select><Input required value={claim.sourceId} onChange={(event) => onChange("sourceId", event.target.value)} placeholder="Source ID" /><Input required value={claim.sourceHash} onChange={(event) => onChange("sourceHash", event.target.value)} placeholder="Immutable source hash" /></div>
  </fieldset>;
}

function ConflictHistory({ conflict }: { conflict: ExecutiveConflictItem }) {
  return <div className="mt-4 space-y-3"><p className="text-sm font-medium text-foreground">{conflict.subject}</p>{conflict.resolutionSummary ? <p className="text-sm text-muted-foreground">{conflict.resolutionSummary}</p> : null}<div className="divide-y divide-border/50">{conflict.claims.map((claim) => <ClaimRow key={claim.id} claim={claim} />)}</div><div className="divide-y divide-border/50">{conflict.history.map((entry) => <div key={entry.id} className="py-3 text-xs text-muted-foreground"><span className="font-medium text-foreground">{label(entry.action)}</span> · {entry.actorLabel} · {date(entry.createdAt)}<br />{entry.rationale}</div>)}</div></div>;
}

export function ExecutiveConflictWorkflow({ briefId }: { briefId: string }) {
  const [feed, setFeed] = useState<ExecutiveConflictFeed | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<ExecutiveConflictItem | null>(null); const [saving, setSaving] = useState(false); const [form, setForm] = useState<CreateForm>(blankForm); const [resolutionSummary, setResolutionSummary] = useState(""); const [operationalMeaning, setOperationalMeaning] = useState("");
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setFeed(await apiFetch<ExecutiveConflictFeed>(`/api/executive/conflicts?briefId=${briefId}`, { cache: "no-store" })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Executive conflicts could not be loaded."); } finally { setLoading(false); } }, [briefId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const openConflicts = useMemo(() => (feed?.conflicts ?? []).filter((conflict) => !["resolved", "dismissed"].includes(conflict.status)), [feed]);
  const closedConflicts = useMemo(() => (feed?.conflicts ?? []).filter((conflict) => ["resolved", "dismissed"].includes(conflict.status)), [feed]);
  const openAttention = useMemo(() => (feed?.attention ?? []).filter((item) => !["resolved", "dismissed"].includes(item.lifecycle)), [feed]);
  const updateClaim = (index: 0 | 1, key: keyof ClaimForm, value: string) => setForm((current) => { const claims = [...current.claims] as [ClaimForm, ClaimForm]; claims[index] = { ...claims[index], [key]: value }; return { ...current, claims }; });
  async function createConflict(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); try { await apiFetch("/api/executive/conflicts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, briefId, dueAt: new Date(form.dueAt).toISOString(), claims: form.claims.map((claim) => ({ ...claim, sourceType: "manual_attestation" })) }) }); setCreating(false); setForm(blankForm()); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Executive conflict could not be recorded."); } finally { setSaving(false); } }
  async function resolveConflict(dismiss = false) { if (!selected) return; setSaving(true); setError(null); try { await apiFetch(`/api/executive/conflicts/${selected.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ briefId, resolutionSummary, currentOperationalMeaning: operationalMeaning, dismiss }) }); setSelected(null); setResolutionSummary(""); setOperationalMeaning(""); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Executive conflict could not be resolved."); } finally { setSaving(false); } }
  return <section className="mt-12 py-2" aria-labelledby="executive-conflicts-heading"><div className="flex flex-wrap items-start justify-between gap-4"><div id="executive-conflicts-heading"><SectionRuleHeading label="Authoritative conflicts" className="mb-1" /><p className="mt-1 text-sm text-muted-foreground">Human-confirmed operational meaning, with competing evidence retained.</p></div><Button size="sm" onClick={() => setCreating(true)}>Record conflict</Button></div>
    {error ? <ErrorState title="Executive conflicts need attention" error={error} className="py-4" /> : null}{loading ? <p className="mt-6 text-sm text-muted-foreground">Loading authoritative conflicts…</p> : null}{!loading && !error && openConflicts.length === 0 ? <p className="mt-6 text-sm text-muted-foreground">No open authoritative conflicts on this Daily Brief.</p> : null}
    {!loading && openConflicts.length > 0 ? <div className="mt-6 divide-y divide-border">{openConflicts.map((conflict) => <div key={conflict.id} className="py-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-foreground">{conflict.subject}</p><p className="mt-1 text-sm text-muted-foreground">{conflict.impactOfDelay}</p><p className="mt-2 text-xs text-muted-foreground">{label(conflict.domain)} · {conflict.ownershipRoute} · resolver {conflict.resolver} · due {date(conflict.dueAt)}{conflict.attentionTitle ? ` · attention: ${conflict.attentionTitle}` : ""}</p></div><Button size="sm" variant="outline" onClick={() => setSelected(conflict)}>Resolve</Button></div><div className="mt-3 divide-y divide-border/50">{conflict.claims.map((claim) => <ClaimRow key={claim.id} claim={claim} />)}</div></div>)}</div> : null}
    {!loading && closedConflicts.length > 0 ? <section className="mt-8 border-t border-border pt-6" aria-labelledby="resolved-conflicts-heading"><SectionRuleHeading label="Resolved conflict history" className="mb-1" /><p id="resolved-conflicts-heading" className="text-sm text-muted-foreground">Human decisions retain the competing claims and every recorded rationale.</p><div className="mt-4 divide-y divide-border">{closedConflicts.map((conflict) => <ConflictHistory key={conflict.id} conflict={conflict} />)}</div></section> : null}
    <Dialog open={creating} onOpenChange={setCreating}><DialogContent className="max-h-screen overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Record authoritative conflict</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={createConflict}><div className="grid gap-4 sm:grid-cols-2"><Select value={form.attentionId} onValueChange={(value) => setForm((current) => ({ ...current, attentionId: value }))}><SelectTrigger aria-label="Attached executive attention"><SelectValue placeholder="Attach open attention" /></SelectTrigger><SelectContent>{openAttention.map((item) => <SelectItem value={item.id} key={item.id}>{item.title}</SelectItem>)}</SelectContent></Select><Select value={form.domain} onValueChange={(value) => setForm((current) => ({ ...current, domain: value as CreateForm["domain"] }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="finance">Finance</SelectItem><SelectItem value="schedule_operations">Schedule and operations</SelectItem><SelectItem value="project">Project</SelectItem><SelectItem value="executive_priority">Executive priority</SelectItem></SelectContent></Select></div><Input required value={form.subject} onChange={(event) => setForm((current) => ({ ...current, subject: event.target.value }))} placeholder="Conflict subject" /><Textarea required value={form.impactOfDelay} onChange={(event) => setForm((current) => ({ ...current, impactOfDelay: event.target.value }))} placeholder="Impact of delay" className="min-h-20" /><div className="grid gap-4 sm:grid-cols-3"><Select value={form.priority} onValueChange={(value) => setForm((current) => ({ ...current, priority: value as CreateForm["priority"] }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="critical">Critical</SelectItem><SelectItem value="high">High</SelectItem><SelectItem value="medium">Medium</SelectItem><SelectItem value="low">Low</SelectItem></SelectContent></Select><Input required value={form.accountableResolverLabel} onChange={(event) => setForm((current) => ({ ...current, accountableResolverLabel: event.target.value }))} placeholder="Resolver" /><Input required type="datetime-local" value={form.dueAt} onChange={(event) => setForm((current) => ({ ...current, dueAt: event.target.value }))} /></div><ClaimInputs index={0} claim={form.claims[0]} onChange={(key, value) => updateClaim(0, key, value)} /><ClaimInputs index={1} claim={form.claims[1]} onChange={(key, value) => updateClaim(1, key, value)} /><DialogFooter><Button type="button" variant="ghost" onClick={() => setCreating(false)}>Cancel</Button><Button type="submit" disabled={saving || !form.attentionId}>{saving ? "Recording…" : "Record conflict"}</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null); }}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Confirm operational meaning</DialogTitle></DialogHeader><div className="space-y-4"><Textarea value={operationalMeaning} onChange={(event) => setOperationalMeaning(event.target.value)} placeholder="What should operators treat as current now?" className="min-h-24" /><Textarea value={resolutionSummary} onChange={(event) => setResolutionSummary(event.target.value)} placeholder="Why is this a human-confirmed resolution?" className="min-h-24" /><p className="text-xs text-muted-foreground">This records a new human resolution. Competing claims and prior history stay immutable.</p></div><DialogFooter><Button variant="ghost" onClick={() => setSelected(null)}>Cancel</Button><Button variant="outline" disabled={saving || resolutionSummary.trim().length < 10 || operationalMeaning.trim().length < 4} onClick={() => void resolveConflict(true)}>Dismiss with rationale</Button><Button disabled={saving || resolutionSummary.trim().length < 10 || operationalMeaning.trim().length < 4} onClick={() => void resolveConflict()}>Confirm resolution</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}
