// AUTO-GENERATED by npm run architecture:changes. Do not edit by hand.

export type ArchitectureChange = {
  taskId: string;
  title: string;
  date: string;
  objective: string;
  whyItMatters: string;
  issueUrl: string;
  repository: string;
  revision: string;
  revisionUrl: string;
  reviewArtifact: string;
  status: "Accepted";
};

export const ARCHITECTURE_CHANGES = [
  {
    "taskId": "AAI-1093",
    "title": "AI Dashboard Architecture Assurance",
    "date": "2026-07-16",
    "objective": "Add a Brandon-facing Architecture Assurance child page to the executive AI workspace that proves Alleato has clear architectural owners, enforced quality gates, and a controlled change path.",
    "whyItMatters": "Leadership can see the existing ownership model and safe change path without receiving repository controls.",
    "issueUrl": "https://linear.app/megankharrison/issue/AAI-1093/add-an-architecture-assurance-page-to-the-executive-ai-workspace",
    "repository": "The-Alleato-Group/project-management",
    "revision": "68c70158d159b0c5ec6f462707d671b02c846b3b",
    "revisionUrl": "https://github.com/The-Alleato-Group/project-management/commit/68c70158d159b0c5ec6f462707d671b02c846b3b",
    "reviewArtifact": "docs/ops/evidence/2026-07-16-ai-dashboard-architecture-assurance/independent-review.md",
    "status": "Accepted"
  },
  {
    "taskId": "AAI-1085",
    "title": "Brandon Architecture Center",
    "date": "2026-07-16",
    "objective": "Publish a concise, Brandon-facing Architecture Center in the Alleato OS docs site that explains product architecture, codebase navigation, and AI ownership without duplicating technical source-of-truth documents.",
    "whyItMatters": "The long-form architecture explanation now has one published home that links back to maintained technical sources.",
    "issueUrl": "https://linear.app/megankharrison/issue/AAI-1085/publish-brandon-facing-architecture-center-on-docs-site",
    "repository": "MeganHarrison/alleato-os",
    "revision": "dff1876711342f5752e2b815ae60409909ab4141",
    "revisionUrl": "https://github.com/MeganHarrison/alleato-os/commit/dff1876711342f5752e2b815ae60409909ab4141",
    "reviewArtifact": "docs/ops/evidence/2026-07-16-brandon-architecture-center/independent-review.md",
    "status": "Accepted"
  }
] as const satisfies readonly ArchitectureChange[];
