-- Give active Project Manager project-role members Commitments read/write.
--
-- Project roles and permission templates are separate concepts. The project
-- shell already accepts project-role membership, but commitment RLS delegates
-- to current_has_project_module_permission(), which previously considered only
-- directory/company templates. Keep explicit user_module_permissions first so
-- an intentional user-level denial still overrides the role-derived grant.
--
-- This migration is forward-only. To reverse the product decision, create a
-- new migration that restores the prior helper body from
-- 20260722173000_atomic_ai_prime_contract_sov_edits.sql. Do not edit this file
-- after it is applied.

begin;

create or replace function public.current_has_project_module_permission(
  p_project_id bigint,
  p_module text,
  p_required_level text
)
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_person_id uuid;
  v_level text;
  v_rules jsonb;
  v_has_project_manager_role boolean := false;
begin
  if p_project_id is null
    or p_module is null
    or p_required_level not in ('read', 'write', 'admin')
  then
    return false;
  end if;

  if public.current_is_app_admin() then
    return true;
  end if;

  v_person_id := public.current_person_id();
  if v_person_id is null then
    return false;
  end if;

  if not exists (
    select 1
    from public.people p
    where p.id = v_person_id
      and p.status = 'active'
  ) then
    return false;
  end if;

  select exists (
    select 1
    from public.project_role_members prm
    join public.project_roles pr
      on pr.id = prm.project_role_id
    where prm.person_id = v_person_id
      and pr.project_id = p_project_id
      and lower(btrim(pr.role_name)) = 'project manager'
  )
  into v_has_project_manager_role;

  if not exists (
    select 1
    from public.project_directory_memberships pdm
    where pdm.project_id = p_project_id
      and pdm.person_id = v_person_id
      and pdm.status = 'active'
  )
  and not exists (
    select 1
    from public.person_company_templates pct
    where pct.person_id = v_person_id
  )
  and not (
    v_has_project_manager_role
    and p_module = 'commitments'
  )
  then
    return false;
  end if;

  select ump.level
  into v_level
  from public.user_module_permissions ump
  where ump.project_id = p_project_id
    and ump.person_id = v_person_id
    and ump.module = p_module
  limit 1;

  if found then
    return case p_required_level
      when 'read' then v_level in ('read', 'write', 'admin')
      when 'write' then v_level in ('write', 'admin')
      when 'admin' then v_level = 'admin'
      else false
    end;
  end if;

  if v_has_project_manager_role
    and p_module = 'commitments'
    and p_required_level in ('read', 'write')
  then
    return true;
  end if;

  select pt.rules_json -> p_module
  into v_rules
  from public.project_directory_memberships pdm
  join public.permission_templates pt
    on pt.id = pdm.permission_template_id
  where pdm.project_id = p_project_id
    and pdm.person_id = v_person_id
    and pdm.status = 'active'
  limit 1;

  if not found then
    select pt.rules_json -> p_module
    into v_rules
    from public.person_company_templates pct
    join public.permission_templates pt
      on pt.id = pct.template_id
    where pct.person_id = v_person_id
    limit 1;
  end if;

  return case p_required_level
    when 'read' then coalesce(v_rules ?| array['read', 'write', 'admin'], false)
    when 'write' then coalesce(v_rules ?| array['write', 'admin'], false)
    when 'admin' then coalesce(v_rules ? 'admin', false)
    else false
  end;
end;
$$;

revoke all on function public.current_has_project_module_permission(
  bigint, text, text
) from public, anon;
grant execute on function public.current_has_project_module_permission(
  bigint, text, text
) to authenticated, service_role;

do $$
declare
  function_definition text;
begin
  select pg_get_functiondef(
    'public.current_has_project_module_permission(bigint,text,text)'::regprocedure
  )
  into function_definition;

  if function_definition not ilike '%join public.project_roles pr%'
    or function_definition not ilike
      '%lower(btrim(pr.role_name)) = ''project manager''%'
    or function_definition not ilike '%p_module = ''commitments''%'
    or function_definition not ilike
      '%p_required_level in (''read'', ''write'')%'
    or function_definition not ilike
      '%v_has_project_manager_role%and p_module = ''commitments''%'
  then
    raise exception
      'Project Manager role commitment access function contract is invalid';
  end if;

  if not has_function_privilege(
    'authenticated',
    'public.current_has_project_module_permission(bigint,text,text)',
    'EXECUTE'
  ) then
    raise exception
      'Project Manager role commitment access verification failed: authenticated cannot execute helper';
  end if;

  if has_function_privilege(
    'anon',
    'public.current_has_project_module_permission(bigint,text,text)',
    'EXECUTE'
  ) then
    raise exception
      'Project Manager role commitment access verification failed: anon can execute helper';
  end if;
end
$$;

commit;
